# Generated by Django 2.2.1 on 2020-05-29 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateField(blank=True, default=None, null=True)),
                ('date_made', models.DateField(blank=True, default=None, null=True)),
                ('date_expired', models.DateField(blank=True, default=None, null=True)),
                ('quantite', models.IntegerField()),
                ('prix_achat_unite', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prix_vent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('somme_money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delai_attente', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.Medicine')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Supplier')),
            ],
            options={
                'ordering': ('date_achat',),
            },
        ),
    ]
