# Generated by Django 2.2.1 on 2020-05-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telephone_number', models.CharField(max_length=10, null=True)),
                ('telephone_number1', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40, null=True)),
                ('address', models.CharField(max_length=100)),
                ('type_people', models.CharField(choices=[('Fornisseur', 'Fornisseur'), ('Client', 'Client')], default='Client', max_length=15)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
