# Generated by Django 2.2.1 on 2020-05-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telephone_number', models.CharField(max_length=10, null=True)),
                ('telephone_number1', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40, null=True)),
                ('address', models.CharField(max_length=100)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telephone_number', models.CharField(max_length=10, null=True)),
                ('telephone_number1', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40, null=True)),
                ('address', models.CharField(max_length=100)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
